#!/usr/bin/env ts-node
/**
 * kamino_stake.ts — Deposit SOL into kSOL vault, receive kSOL tokens.
 *
 * Calls vault.deposit() on the mock-staking program.
 * SOL is locked in the vault PDA; program mints kSOL to recipient.
 *
 * Usage:
 *   node scripts/dist/kamino_stake.js <recipient_b58> <amount_lamports> <rpc_url> <solver_private_key>
 *
 * Outputs on stdout (for Rust caller to parse):
 *   TOKEN_MINTED:<shares>
 *
 * Reads mint address from scripts/mock_tokens.json (created by create_mock_tokens.js).
 * Reads IDL from target/idl/mock_staking.json (generated by anchor build).
 */

import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
} from '@solana/web3.js';
import { getAssociatedTokenAddressSync, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID } from '@solana/spl-token';
import * as anchor from '@coral-xyz/anchor';
import * as fs from 'fs';
import * as path from 'path';

// ──────────────────────────────────────────────────────────────────────────────
// Arguments
// ──────────────────────────────────────────────────────────────────────────────

const [, , recipientB58, amountLamportsStr, rpcUrl, privateKeyArg] = process.argv;

if (!recipientB58 || !amountLamportsStr || !rpcUrl || !privateKeyArg) {
  console.error('Usage: kamino_stake.js <recipient_b58> <amount_lamports> <rpc_url> <solver_private_key>');
  process.exit(1);
}

const amountLamports = BigInt(amountLamportsStr);

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

function loadKeypair(key: string): Keypair {
  const k = key.trim();
  if (k.length === 88) {
    try {
      const bytes = Buffer.from(require('bs58').decode(k));
      if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
    } catch {}
  }
  const hex = k.replace(/^0x/, '');
  const bytes = Buffer.from(hex, 'hex');
  if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
  if (bytes.length === 32) return Keypair.fromSeed(bytes);
  throw new Error(`Invalid private key length: ${bytes.length} bytes`);
}

function loadMintAddress(): string {
  if (process.env.MOCK_KSOL_MINT) return process.env.MOCK_KSOL_MINT;
  const configFile = path.join(__dirname, 'mock_tokens.json');
  if (!fs.existsSync(configFile)) {
    throw new Error(`mock_tokens.json not found at ${configFile}. Run create_mock_tokens.js first.`);
  }
  const config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
  if (!config.kSOL) throw new Error('kSOL mint not found in mock_tokens.json');
  return config.kSOL;
}

function loadIdl(): any {
  const idlPath = path.join(__dirname, '../../target/idl/mock_staking.json');
  if (!fs.existsSync(idlPath)) {
    throw new Error(`IDL not found at ${idlPath}. Run 'anchor build' first.`);
  }
  return JSON.parse(fs.readFileSync(idlPath, 'utf8'));
}

// ──────────────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────────────

async function main() {
  const connection = new Connection(rpcUrl, 'confirmed');
  const solver = loadKeypair(privateKeyArg);
  const recipient = new PublicKey(recipientB58);
  const mintAddress = loadMintAddress();
  const mint = new PublicKey(mintAddress);
  const idl = loadIdl();

  console.error(`Solver:    ${solver.publicKey.toBase58()}`);
  console.error(`Recipient: ${recipient.toBase58()}`);
  console.error(`Amount:    ${amountLamports} lamports`);
  console.error(`kSOL Mint: ${mintAddress}`);

  // Set up Anchor provider
  const wallet = new anchor.Wallet(solver);
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' });
  const program = new anchor.Program(idl, provider);

  // Derive vault PDA
  const [vaultState] = PublicKey.findProgramAddressSync(
    [Buffer.from('vault'), mint.toBuffer()],
    program.programId,
  );
  console.error(`Vault PDA: ${vaultState.toBase58()}`);

  // Fetch current exchange rate
  const vaultAccount = await (program.account as any).vaultState.fetch(vaultState);
  const exchangeRate = BigInt(vaultAccount.exchangeRate.toString());
  const shares = (amountLamports * 1_000_000n) / exchangeRate;
  console.error(`Exchange rate: ${exchangeRate}, shares: ${shares}`);

  // Derive recipient ATA (will be created by the instruction if needed)
  const recipientAta = getAssociatedTokenAddressSync(mint, recipient);
  console.error(`Recipient kSOL ATA: ${recipientAta.toBase58()}`);

  // Call vault.deposit
  const txSig = await (program.methods as any)
    .deposit(new anchor.BN(amountLamports.toString()))
    .accounts({
      depositor: solver.publicKey,
      recipient,
      vaultState,
      mint,
      recipientAta,
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    })
    .signers([solver])
    .rpc({ commitment: 'confirmed' });

  console.error(`Deposit confirmed: ${txSig}`);
  console.log(`TOKEN_MINTED:${shares}`);
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`kamino_stake.ts error: ${msg}`);
  process.exit(1);
});
