#!/usr/bin/env ts-node
/**
 * bump_rate.ts — Admin script to update vault exchange rate (simulate yield).
 *
 * Exchange rate format: 1_000_000 = 1.0x (6 decimal precision)
 * Examples:
 *   1_000_000 = 1.0  (initial, 1:1)
 *   1_050_000 = 1.05 (5% yield accrued)
 *   1_059_000 = 1.059 (5.9% yield accrued)
 *
 * At rate R, redeeming N tokens gives N * R / 1_000_000 lamports.
 *
 * Usage:
 *   node scripts/dist/bump_rate.js <mint_address> <new_rate> <rpc_url> <authority_private_key>
 *
 * Examples:
 *   # Set jitoSOL to 5.9% yield
 *   node scripts/dist/bump_rate.js <jitoSOL_mint> 1059000 <rpc_url> <admin_key>
 *
 * Reads IDL from target/idl/mock_staking.json (generated by anchor build).
 */

import {
  Connection,
  Keypair,
  PublicKey,
} from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import * as fs from 'fs';
import * as path from 'path';

// ──────────────────────────────────────────────────────────────────────────────
// Arguments
// ──────────────────────────────────────────────────────────────────────────────

const [, , mintAddress, newRateStr, rpcUrl, privateKeyArg] = process.argv;

if (!mintAddress || !newRateStr || !rpcUrl || !privateKeyArg) {
  console.error('Usage: bump_rate.js <mint_address> <new_rate> <rpc_url> <authority_private_key>');
  console.error('Example: bump_rate.js <jitoSOL_mint> 1059000 <rpc_url> <admin_key>');
  console.error('  Rate 1059000 = 1.059x = 5.9% yield accrued');
  process.exit(1);
}

const newRate = parseInt(newRateStr, 10);
if (isNaN(newRate) || newRate <= 0) {
  console.error(`Invalid rate: ${newRateStr}. Must be a positive integer (e.g. 1059000 for 5.9% yield)`);
  process.exit(1);
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

function loadKeypair(key: string): Keypair {
  const k = key.trim();
  if (k.length === 88) {
    try {
      const bytes = Buffer.from(require('bs58').decode(k));
      if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
    } catch {}
  }
  const hex = k.replace(/^0x/, '');
  const bytes = Buffer.from(hex, 'hex');
  if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
  if (bytes.length === 32) return Keypair.fromSeed(bytes);
  throw new Error(`Invalid private key length: ${bytes.length} bytes`);
}

function loadIdl(): any {
  const idlPath = path.join(__dirname, '../../target/idl/mock_staking.json');
  if (!fs.existsSync(idlPath)) {
    throw new Error(`IDL not found at ${idlPath}. Run 'anchor build' first.`);
  }
  return JSON.parse(fs.readFileSync(idlPath, 'utf8'));
}

// ──────────────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────────────

async function main() {
  const connection = new Connection(rpcUrl, 'confirmed');
  const authority = loadKeypair(privateKeyArg);
  const mint = new PublicKey(mintAddress);
  const idl = loadIdl();

  console.log(`Authority: ${authority.publicKey.toBase58()}`);
  console.log(`Mint:      ${mintAddress}`);
  console.log(`New rate:  ${newRate} (= ${(newRate / 1_000_000).toFixed(6)}x)`);

  const wallet = new anchor.Wallet(authority);
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' });
  const program = new anchor.Program(idl, provider);

  // Derive vault PDA
  const [vaultState] = PublicKey.findProgramAddressSync(
    [Buffer.from('vault'), mint.toBuffer()],
    program.programId,
  );
  console.log(`Vault PDA: ${vaultState.toBase58()}`);

  // Fetch current rate
  const vaultAccount = await (program.account as any).vaultState.fetch(vaultState);
  const oldRate = vaultAccount.exchangeRate.toNumber();
  console.log(`Current rate: ${oldRate} (= ${(oldRate / 1_000_000).toFixed(6)}x)`);

  if (newRate === oldRate) {
    console.log('Rate unchanged, skipping update.');
    return;
  }

  // Call update_rate
  const txSig = await (program.methods as any)
    .updateRate(new anchor.BN(newRate))
    .accounts({
      authority: authority.publicKey,
      vaultState,
    })
    .signers([authority])
    .rpc({ commitment: 'confirmed' });

  console.log(`Rate updated! tx: ${txSig}`);
  console.log(`  ${oldRate} → ${newRate} (${((newRate - 1_000_000) / 10_000).toFixed(2)}% yield)`);
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`bump_rate.ts error: ${msg}`);
  process.exit(1);
});
