#!/usr/bin/env ts-node
/**
 * initialize_vault.ts — One-time setup: initialize vault PDAs for each mock token.
 *
 * For each mint (jitoSOL, jupSOL, kSOL):
 *   1. Creates a VaultState PDA with exchange_rate = 1_000_000 (1:1)
 *   2. Transfers mint authority from admin to vault PDA
 *
 * After this, only the vault program can mint/burn tokens.
 * Admin (solver keypair) must be the current mint authority.
 *
 * Usage:
 *   node scripts/dist/initialize_vault.js <rpc_url> <admin_private_key>
 *
 * Reads mint addresses from scripts/mock_tokens.json (created by create_mock_tokens.js).
 * Reads IDL from target/idl/mock_staking.json (generated by anchor build).
 */

import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
} from '@solana/web3.js';
import { TOKEN_PROGRAM_ID } from '@solana/spl-token';
import * as anchor from '@coral-xyz/anchor';
import * as fs from 'fs';
import * as path from 'path';

// ──────────────────────────────────────────────────────────────────────────────
// Arguments
// ──────────────────────────────────────────────────────────────────────────────

const [, , rpcUrl, privateKeyArg] = process.argv;

if (!rpcUrl || !privateKeyArg) {
  console.error('Usage: initialize_vault.js <rpc_url> <admin_private_key>');
  process.exit(1);
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

function loadKeypair(key: string): Keypair {
  const k = key.trim();
  if (k.length === 88) {
    try {
      const bytes = Buffer.from(require('bs58').decode(k));
      if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
    } catch {}
  }
  const hex = k.replace(/^0x/, '');
  const bytes = Buffer.from(hex, 'hex');
  if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
  if (bytes.length === 32) return Keypair.fromSeed(bytes);
  throw new Error(`Invalid private key length: ${bytes.length} bytes`);
}

function loadMockTokens(): { jitoSOL: string; jupSOL: string; kSOL: string } {
  const configFile = path.join(__dirname, 'mock_tokens.json');
  if (!fs.existsSync(configFile)) {
    throw new Error(`mock_tokens.json not found at ${configFile}. Run create_mock_tokens.js first.`);
  }
  const config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
  if (!config.jitoSOL || !config.jupSOL || !config.kSOL) {
    throw new Error('mock_tokens.json missing one or more mints (jitoSOL, jupSOL, kSOL)');
  }
  return config;
}

function loadIdl(): any {
  const idlPath = path.join(__dirname, '../../target/idl/mock_staking.json');
  if (!fs.existsSync(idlPath)) {
    throw new Error(`IDL not found at ${idlPath}. Run 'anchor build' first.`);
  }
  return JSON.parse(fs.readFileSync(idlPath, 'utf8'));
}

// ──────────────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────────────

const INITIAL_EXCHANGE_RATE = 1_000_000; // 1:1 (1 SOL = 1 token)

async function initVault(
  program: anchor.Program,
  admin: Keypair,
  mintAddress: string,
  label: string,
): Promise<void> {
  const mint = new PublicKey(mintAddress);

  const [vaultState] = PublicKey.findProgramAddressSync(
    [Buffer.from('vault'), mint.toBuffer()],
    program.programId,
  );

  // Check if already initialized
  try {
    const existing = await (program.account as any).vaultState.fetch(vaultState);
    console.log(`[${label}] Vault already initialized at ${vaultState.toBase58()}, rate=${existing.exchangeRate}`);
    return;
  } catch {
    // Not initialized yet — proceed
  }

  console.log(`[${label}] Initializing vault at ${vaultState.toBase58()}...`);
  console.log(`[${label}]   Mint: ${mintAddress}`);
  console.log(`[${label}]   Rate: ${INITIAL_EXCHANGE_RATE} (1:1)`);

  const txSig = await (program.methods as any)
    .initializeVault(new anchor.BN(INITIAL_EXCHANGE_RATE))
    .accounts({
      authority: admin.publicKey,
      vaultState,
      mint,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
    })
    .signers([admin])
    .rpc({ commitment: 'confirmed' });

  console.log(`[${label}] Vault initialized! tx: ${txSig}`);
  console.log(`[${label}]   VaultState PDA: ${vaultState.toBase58()}`);
  console.log(`[${label}]   Mint authority transferred to vault PDA`);
}

async function main() {
  const connection = new Connection(rpcUrl, 'confirmed');
  const admin = loadKeypair(privateKeyArg);
  const tokens = loadMockTokens();
  const idl = loadIdl();

  console.log(`Admin: ${admin.publicKey.toBase58()}`);
  console.log(`Program: ${idl.address || idl.metadata?.address}`);

  const wallet = new anchor.Wallet(admin);
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' });
  const program = new anchor.Program(idl, provider);

  await initVault(program, admin, tokens.jitoSOL, 'jitoSOL');
  await initVault(program, admin, tokens.jupSOL, 'jupSOL');
  await initVault(program, admin, tokens.kSOL, 'kSOL');

  console.log('\nAll vaults initialized successfully!');
  console.log('Users can now deposit SOL and receive yield-bearing tokens.');
  console.log('Use bump_rate.js to simulate yield accrual.');
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`initialize_vault.ts error: ${msg}`);
  process.exit(1);
});
