#!/usr/bin/env ts-node
/**
 * jupsol_unstake.ts — Build an unsigned VersionedTransaction to redeem jupSOL for SOL.
 *
 * Calls vault.redeem() on the mock-staking program.
 * Vault burns the user's jupSOL and sends SOL * exchange_rate back — only user needs to sign!
 * No solver pre-signing needed (unlike the old burn+transfer approach).
 *
 * Usage:
 *   node scripts/dist/jupsol_unstake.js <wallet_pubkey> <amount_raw> <rpc_url> <solver_private_key>
 *
 * Outputs on stdout: base64-encoded unsigned VersionedTransaction.
 * The frontend wallet adapter provides the user's signature.
 *
 * Reads mint address from scripts/mock_tokens.json.
 * Reads IDL from target/idl/mock_staking.json (generated by anchor build).
 */

import {
  Connection,
  Keypair,
  PublicKey,
  TransactionMessage,
  VersionedTransaction,
} from '@solana/web3.js';
import { getAssociatedTokenAddressSync, TOKEN_PROGRAM_ID } from '@solana/spl-token';
import * as anchor from '@coral-xyz/anchor';
import * as fs from 'fs';
import * as path from 'path';

// ──────────────────────────────────────────────────────────────────────────────
// Arguments
// ──────────────────────────────────────────────────────────────────────────────

const [, , walletB58, amountRawStr, rpcUrl, privateKeyArg] = process.argv;

if (!walletB58 || !amountRawStr || !rpcUrl || !privateKeyArg) {
  console.error('Usage: jupsol_unstake.js <wallet_pubkey> <amount_raw> <rpc_url> <solver_private_key>');
  process.exit(1);
}

const amountRaw = BigInt(amountRawStr);

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

function loadKeypair(key: string): Keypair {
  const k = key.trim();
  if (k.length === 88) {
    try {
      const bytes = Buffer.from(require('bs58').decode(k));
      if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
    } catch {}
  }
  const hex = k.replace(/^0x/, '');
  const bytes = Buffer.from(hex, 'hex');
  if (bytes.length === 64) return Keypair.fromSecretKey(bytes);
  if (bytes.length === 32) return Keypair.fromSeed(bytes);
  throw new Error(`Invalid private key length: ${bytes.length} bytes`);
}

function loadMintAddress(): string {
  if (process.env.MOCK_JUPSOL_MINT) return process.env.MOCK_JUPSOL_MINT;
  const configFile = path.join(__dirname, 'mock_tokens.json');
  if (!fs.existsSync(configFile)) throw new Error(`mock_tokens.json not found at ${configFile}`);
  const config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
  if (!config.jupSOL) throw new Error('jupSOL mint not found in mock_tokens.json');
  return config.jupSOL;
}

function loadIdl(): any {
  const idlPath = path.join(__dirname, '../../target/idl/mock_staking.json');
  if (!fs.existsSync(idlPath)) {
    throw new Error(`IDL not found at ${idlPath}. Run 'anchor build' first.`);
  }
  return JSON.parse(fs.readFileSync(idlPath, 'utf8'));
}

// ──────────────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────────────

async function main() {
  const connection = new Connection(rpcUrl, 'confirmed');
  const solver = loadKeypair(privateKeyArg);
  const userWallet = new PublicKey(walletB58);
  const mint = new PublicKey(loadMintAddress());
  const idl = loadIdl();

  console.error(`Wallet:      ${userWallet.toBase58()}`);
  console.error(`Amount raw:  ${amountRaw}`);
  console.error(`jupSOL Mint: ${mint.toBase58()}`);

  // Set up Anchor provider (solver keypair used only to satisfy provider interface)
  const wallet = new anchor.Wallet(solver);
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' });
  const program = new anchor.Program(idl, provider);

  // Derive vault PDA
  const [vaultState] = PublicKey.findProgramAddressSync(
    [Buffer.from('vault'), mint.toBuffer()],
    program.programId,
  );
  console.error(`Vault PDA: ${vaultState.toBase58()}`);

  const userAta = getAssociatedTokenAddressSync(mint, userWallet);
  console.error(`User jupSOL ATA: ${userAta.toBase58()}`);

  // Build vault.redeem instruction — only user needs to sign
  const ix = await (program.methods as any)
    .redeem(new anchor.BN(amountRaw.toString()))
    .accounts({
      user: userWallet,
      vaultState,
      mint,
      userAta,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .instruction();

  const { blockhash } = await connection.getLatestBlockhash('confirmed');
  const message = new TransactionMessage({
    payerKey: userWallet,
    recentBlockhash: blockhash,
    instructions: [ix],
  }).compileToV0Message();

  const tx = new VersionedTransaction(message);
  // No pre-signing needed — user is the only required signer

  const serialized = Buffer.from(tx.serialize());
  console.log(serialized.toString('base64'));
  console.error('jupSOL redeem tx built. Awaiting user signature.');
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`jupsol_unstake.ts error: ${msg}`);
  process.exit(1);
});
